name: cron
on:
  schedule:
    - cron: '39 * * * *'
jobs:
  update_changelogs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: crawl git repo to update changelog files
        run: poetry run python -m crawler.crawl
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updating CHANGELOG"
          file_pattern: "*.md"